"""empty message

Revision ID: 11acea7b8113
Revises: 1a75c2c6e46
Create Date: 2014-08-09 17:26:03.159842

"""

# revision identifiers, used by Alembic.
revision = '11acea7b8113'
down_revision = '1a75c2c6e46'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'count')
    ### end Alembic commands ###
