"""empty message

Revision ID: 1a75c2c6e46
Revises: 26aa655fb5f
Create Date: 2014-08-09 04:19:26.346817

"""

# revision identifiers, used by Alembic.
revision = '1a75c2c6e46'
down_revision = '26aa655fb5f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
