"""empty message

Revision ID: 1e6a6f1e23b
Revises: 28839f3e9a92
Create Date: 2014-08-06 19:34:13.712116

"""

# revision identifiers, used by Alembic.
revision = '1e6a6f1e23b'
down_revision = '28839f3e9a92'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    ### end Alembic commands ###
