"""empty message

Revision ID: 26aa655fb5f
Revises: 24ba65ede62e
Create Date: 2014-08-09 03:32:57.043346

"""

# revision identifiers, used by Alembic.
revision = '26aa655fb5f'
down_revision = '24ba65ede62e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'count')
    ### end Alembic commands ###
