"""empty message

Revision ID: 28839f3e9a92
Revises: None
Create Date: 2014-08-06 18:57:57.700952

"""

# revision identifiers, used by Alembic.
revision = '28839f3e9a92'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
