"""empty message

Revision ID: 29141588d861
Revises: 593d861a2447
Create Date: 2014-08-08 19:24:10.739690

"""

# revision identifiers, used by Alembic.
revision = '29141588d861'
down_revision = '593d861a2447'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('password', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'password')
    ### end Alembic commands ###
